version: "3"
services:
  container_name: backend
  build:
    context: ./
    dockerfile: Dockerfile
  volumes:
    - ./src/main/resources:/src/main/resources
  ports:
    - "8080:8080"
  volumes:
    - './jenkins_home:/var/jenkins_home'
    - '/var/run/docker.sock:/var/run/docker.sock'
  restart: always